// Common ad, tracker, and analytics domains
// Matched against the hostname of proxied requests
const BLOCKED_DOMAINS = new Set([
  // Google Ads & Analytics
  'googleads.g.doubleclick.net',
  'pagead2.googlesyndication.com',
  'adservice.google.com',
  'www.googleadservices.com',
  'googleadservices.com',
  'googlesyndication.com',
  'www.googlesyndication.com',
  'tpc.googlesyndication.com',
  'doubleclick.net',
  'www.doubleclick.net',
  'ad.doubleclick.net',
  'stats.g.doubleclick.net',
  'www.google-analytics.com',
  'google-analytics.com',
  'ssl.google-analytics.com',
  'analytics.google.com',
  'www.googletagmanager.com',
  'googletagmanager.com',
  'www.googletagservices.com',
  'googletagservices.com',
  'pagead-googlehosted.l.google.com',

  // Facebook / Meta
  'www.facebook.com/tr',
  'connect.facebook.net',
  'pixel.facebook.com',
  'www.facebook.com/plugins',
  'graph.facebook.com',

  // Amazon Ads
  'aax.amazon-adsystem.com',
  'z-na.amazon-adsystem.com',
  'fls-na.amazon-adsystem.com',
  'amazon-adsystem.com',

  // Common ad networks
  'ads.yahoo.com',
  'ad.yieldmanager.com',
  'serving-sys.com',
  'bs.serving-sys.com',
  'adnxs.com',
  'ib.adnxs.com',
  'secure.adnxs.com',
  'cdn.taboola.com',
  'trc.taboola.com',
  'api.taboola.com',
  'taboola.com',
  'cdn.outbrain.com',
  'outbrain.com',
  'widgets.outbrain.com',
  'revolvermaps.com',
  'ads.pubmatic.com',
  'pubmatic.com',
  'openx.net',
  'us-u.openx.net',
  'rtb.openx.net',
  'prebid.adnxs.com',
  'match.adsrvr.org',
  'adsrvr.org',
  'ad.turn.com',
  'ads.rubiconproject.com',
  'rubiconproject.com',
  'fastclick.net',
  'media.net',
  'static.media.net',
  'contextweb.com',
  'revcontent.com',
  'mgid.com',

  // Trackers & analytics
  'scorecardresearch.com',
  'sb.scorecardresearch.com',
  'b.scorecardresearch.com',
  'quantserve.com',
  'pixel.quantserve.com',
  'edge.quantserve.com',
  'quantcount.com',
  'bluekai.com',
  'tags.bluekai.com',
  'stags.bluekai.com',
  'krxd.net',
  'beacon.krxd.net',
  'cdn.krxd.net',
  'exelator.com',
  'loadm.exelator.com',
  'demdex.net',
  'dpm.demdex.net',
  'omtrdc.net',
  'everesttech.net',
  'crwdcntrl.net',
  'bkrtx.com',
  'adsymptotic.com',
  'adform.net',
  'serving.track.adform.net',
  'track.adform.net',
  'hotjar.com',
  'static.hotjar.com',
  'script.hotjar.com',
  'vars.hotjar.com',
  'mouseflow.com',
  'a.mouseflow.com',
  'fullstory.com',
  'rs.fullstory.com',
  'heapanalytics.com',
  'cdn.heapanalytics.com',
  'mixpanel.com',
  'cdn.mxpnl.com',
  'api.mixpanel.com',
  'amplitude.com',
  'api.amplitude.com',
  'cdn.amplitude.com',
  'segment.io',
  'cdn.segment.io',
  'api.segment.io',
  'segment.com',
  'cdn.segment.com',

  // Popups & malvertising
  'popads.net',
  'popcash.net',
  'propellerads.com',
  'ad.propellerads.com',
  'adcash.com',
  'bidvertiser.com',
  'clickadu.com',
  'hilltopads.net',
  'exoclick.com',
  'juicyads.com',
  'trafficjunky.com',

  // Social tracking widgets
  'platform.twitter.com',
  'syndication.twitter.com',
  'static.ads-twitter.com',
  'analytics.twitter.com',
  'platform.linkedin.com',
  'snap.licdn.com',

  // Other common trackers
  'bat.bing.com',
  'clarity.ms',
  'www.clarity.ms',
  'newrelic.com',
  'js-agent.newrelic.com',
  'bam.nr-data.net',
  'crashlytics.com',
  'settings.crashlytics.com',
  'sentry.io',
  'cdn.ravenjs.com',
  'bugsnag.com',
  'notify.bugsnag.com',
  'app.pendo.io',
  'pendo-io-static.storage.googleapis.com',
  'cdn.cookielaw.org',
  'geolocation.onetrust.com',
  'cdn.onetrust.com',
]);

// Patterns that match subdomains (checked with endsWith)
const BLOCKED_SUFFIXES = [
  '.doubleclick.net',
  '.googlesyndication.com',
  '.googleadservices.com',
  '.moatads.com',
  '.amazon-adsystem.com',
  '.2mdn.net',
  '.adnxs.com',
  '.adsrvr.org',
  '.demdex.net',
  '.omtrdc.net',
  '.krxd.net',
  '.bluekai.com',
  '.exelator.com',
  '.crwdcntrl.net',
  '.hotjar.com',
  '.taboola.com',
  '.outbrain.com',
];

function isBlocked(hostname) {
  if (BLOCKED_DOMAINS.has(hostname)) return true;
  for (const suffix of BLOCKED_SUFFIXES) {
    if (hostname.endsWith(suffix)) return true;
  }
  return false;
}

module.exports = { isBlocked };
